### ISSUE TITLE
gsplat installation dependency may need clarification? ImportError: cannot import name 'csrc' from 'gsplat'

### ISSUE THREAD

**Issue by luckui** [apple/ml-sharp#47]
**Description**  
When trying to use this project on Windows with an RTX 4080, I noticed that the documentation recommends torch 2.8.0. However, in practice, GSPLAT's CUDA extensions do not seem to compile successfully with PyTorch 2.8.0.

**Issues encountered**  
- Errors like `ImportError: cannot import name 'csrc' from 'gsplat'`
- Runtime errors during CUDA extension compilation
- `_jit_compile() missing 2 required positional arguments: 'verbose' and 'with_sycl'`

It would be helpful if the documentation or requirements could clarify:
- The currently recommended PyTorch + CUDA combination
- That using the latest PyTorch version may cause GSPLAT compilation to fail

**Environment**
- Windows 11
- Python 3.13
- PyTorch 2.8.0+ CUDA 12.4
- RTX 4080

Community examples and some testing indicate that GSPLAT extensions can successfully build with torch 2.1.2 + CUDA 11.8. This might be useful information for users trying to run this project on Windows. https://github.com/nerfstudio-project/gsplat/issues/311
Am I out of date?

**Request**  
I am looking for guidance or instructions on how to successfully install and compile GSPLAT under these conditions. Any help would be appreciated.
